excluded: # paths to ignore during linting.
  - Example/Pods
identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
type_name:
  min_length: 1
line_length:
  warning: 170
file_length:
  max_length: 1000
disabled_rules:
  - function_parameter_count
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - trailing_whitespace
  - redundant_string_enum_value
